### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by abanghendri** [iotronlab/filament-multi-guard#4]
### What happened?

I change color by following this [documentation](https://filamentphp.com/docs/2.x/admin/appearance#building-themes)
but unfortunately, only default filament that changed, not with my custom context

how to achieve that?

### How to reproduce the bug

follow the documentation [here](https://filamentphp.com/docs/2.x/admin/appearance#building-themes) to change filament color

### Package Version

1.0

### PHP Version

8.2.6

### Laravel Version

10.10

### Which operating systems does with happen with?

Linux

**Comment by iotron** [comment]
Theme is working with multiple context. Make sure you have included this code in AppServiceProvider.php
```
use Filament\Facades\Filament;
 
Filament::serving(function () {
    // Using Vite
    Filament::registerViteTheme('resources/css/filament.css');
 
    // Using Laravel Mix
    Filament::registerTheme(
        mix('css/filament.css'),
    );
});
```
