### ISSUE TITLE
[Bug]: Filament v3 upgrade

### ISSUE THREAD

**Issue by martin-arvisais** [iotronlab/filament-multi-guard#9]
### What happened?

I would like to complete my upgrade to Filament v3. Do you plan to make this wonderful package of yours compatible with Filament v3?

### How to reproduce the bug

Upgrade Filament v2 to v3

### Package Version

1.*

### PHP Version

8.2

### Laravel Version

9.*

### Which operating systems does with happen with?

macOS

### Notes

Thank you for the great work!

**Comment by sakanjo** [comment]
I think this plugin is unnecessary anymore, since filamentphp v3 already does multiple guards by default.

**Comment by emiliosh** [comment]
> I think this plugin is unnecessary anymore, since filamentphp v3 already does multiple guards by default.

Where did you find documentation about multiple guards in Filament v3?  I just find $panel->authGuard(string $guard = 'web') only accepting a string.

Thanks in advance.

**Comment by sakanjo** [comment]
@emiliosh https://filamentphp.com/docs/3.x/panels/configuration.
